#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication `getApplication`

runApplication yPlusLESWCompressible -compressible
runApplication foamCalc addSubtract yPlus subtract -field yPlusLES -resultName yPerror -time "0.001:"
